#!/usr/bin/python3.4
# -*-coding:UTF8 -*

#    'X' is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    'X' is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with 'X'.  If not, see <http://www.gnu.org/licenses/>.

from argparse import ArgumentParser
from dbus import SessionBus
from time import sleep

# Récupération des arguments en ligne de commande
parser = ArgumentParser(prog='evening-music-py', description="""Pause amarok at end of timer""")
parser.add_argument('time', nargs='?', action="store", type=int, default="30", help='timer (default : 30)')
parser.add_argument('format', nargs='?', action="store", type=str, default="m", help='s/m/h (default : m)')
args = parser.parse_args()
timer =int(args.time)
form = str(args.format)

# Initialisation de DBus
bus = SessionBus()
session = bus.get_object('org.kde.amarok', '/Player')
get_status = session.get_dbus_method('GetStatus')
pause = session.get_dbus_method('Pause')
status = get_status()
status = status.index(0)

# Algo
if status!=0:
    print("Amarok est déjà en pause")
elif status==0:
    if form=='s':
        time = timer
    elif form=='m':
        time = timer*60
    elif form=='h':
        time = timer*3600
    else:
        print("usage: evening-music-py [-h] [time] [format]\nevening-music-py: error: argument format: Must be [s/m/h] but not '{}'".format(form))
        exit(1)
    print('Amarok sera mis en pause dans {0}{1}'.format(timer, form))
    try:
        sleep(time)
        pause()
    except KeyboardInterrupt as err:
        print('\x0DKeyboardInterrupt, Exiting')
