#!/usr/bin/python3.4
# -*-coding:UTF8 -*

# Copyright 2016 Charles Daudré-Vignier <daudre.vignier.charles@narod.ru>

#    'pyc-read' is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    'pyc-read' is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with 'pyc-read'.  If not, see <http://www.gnu.org/licenses/>.


import imp
import dis
from os.path import basename, splitext
from sys import argv
 
path = argv[-1]
print(path)
base = basename(path)
name, ext = splitext(base)
 
print("Disassembling '%s'...\n" % base)
 
module = imp.load_module(name,
                         open(path, 'rb'),
                         path,
                         ('.pyc', 'rb', imp.PY_COMPILED))
 
dis.dis(module)
